debug: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
     database: H2
     show_sql: true
     open-in-view: false
     hibernate:
       ddl-auto: create-drop
       naming:
         implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
         physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
     properties:
       hibernate.cache.use_second_level_cache: true
       hibernate.cache.use_query_cache: false
  datasource:
     url: jdbc:h2:mem:srf;DB_CLOSE_DELAY=-1
     name:
     username: sa
     password:

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

security:
  headers:
    frame: false